name: musk-sentiment
channels:
  - pytorch
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - annotated-types=0.6.0
  - antlr-python-runtime=4.9.3
  - anyio=4.6.2
  - arrow=1.3.0
  - arrow-cpp=17.0.0
  - async-timeout=5.0.1
  - attrs=24.3.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - binaryornot=0.4.4
  - black=24.10.0
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.12.31
  - chardet=4.0.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - contourpy=1.3.0
  - cookiecutter=2.6.0
  - cudatoolkit=11.8.0
  - cycler=0.12.1
  - datasets=2.19.1
  - dill=0.3.8
  - exceptiongroup=1.2.0
  - fastapi=0.112.2
  - fonttools=4.55.3
  - freetype=2.12.1
  - frozenlist=1.5.0
  - fsspec=2024.3.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - giflib=5.2.2
  - glib=2.80.2
  - glib-tools=2.80.2
  - glog=0.5.0
  - gmpy2=2.1.2
  - gst-plugins-base=1.22.9
  - gstreamer=1.22.9
  - h11=0.14.0
  - hydra-core=1.3.2
  - icu=70.1
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - iniconfig=2.0.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.7
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcurl=8.11.1
  - libdeflate=1.22
  - libevent=2.1.12
  - libffi=3.4.2
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libglib=2.80.2
  - libgrpc=1.62.2
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libogg=1.3.5
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libsqlite=3.48.0
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.12.7
  - libzlib=1.2.13
  - loguru=0.7.2
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - multidict=6.1.0
  - multiprocess=0.70.15
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - networkx=3.2.1
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - omegaconf=2.3.0
  - openjpeg=2.5.2
  - openssl=3.4.0
  - orc=2.0.1
  - pandas=2.2.3
  - pathspec=0.12.1
  - patsy=1.0.1
  - pcre2=10.43
  - pillow=11.0.0
  - pip=24.2
  - platformdirs=4.3.6
  - pluggy=1.5.0
  - ply=3.11
  - propcache=0.2.0
  - pyarrow=17.0.0
  - pydantic=1.10.7
  - pydantic-core=2.27.1
  - pyparsing=3.2.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - pytest=8.3.4
  - python=3.9.21
  - python-dateutil=2.9.0post0
  - python-slugify=5.0.2
  - python-tzdata=2023.3
  - python-xxhash=3.5.0
  - python_abi=3.9
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt-main=5.15.8
  - re2=2022.04.01
  - requests=2.32.3
  - safetensors=0.4.5
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - sqlite=3.45.3
  - starlette=0.38.2
  - statsmodels=0.14.4
  - sympy=1.13.3
  - tbb=2021.8.0
  - text-unidecode=1.3
  - threadpoolctl=3.5.0
  - toml=0.10.2
  - tomli=2.2.1
  - torchdata=0.9.0
  - tornado=6.4.2
  - tqdm=4.66.5
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - ucrt=10.0.22621.0
  - unicodedata2=16.0.0
  - unidecode=1.3.8
  - utf8proc=2.6.1
  - uvicorn=0.32.1
  - vc=14.40
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - wheel=0.44.0
  - win32_setctime=1.1.0
  - win_inet_pton=1.1.0
  - xxhash=0.8.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.18.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - certifi==2024.8.30
      - cloudpickle==3.1.1
      - filelock==3.16.1
      - huggingface-hub==0.25.1
      - idna==3.10
      - llvmlite==0.43.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - numba==0.60.0
      - packaging==24.1
      - pip-check==2.9
      - pipdeptree==2.24.0
      - pygments==2.18.0
      - regex==2024.9.11
      - rich==13.9.2
      - ruff==0.9.2
      - terminaltables==3.1.10
      - tokenizers==0.20.0
      - torch==2.4.1
      - torchvision==0.19.1
      - transformers==4.45.1
      - urllib3==2.2.3
      - zipp==3.20.2
